fail_fast: false

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [ '--line-length', '100' ]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
    - id: blacken-docs
      args: [ '--line-length', '100' ]
      additional_dependencies: [black==21.7b0]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    - id: forbid-crlf
    - id: remove-crlf
    # Black does not clear tabs in docstrings
    - id: forbid-tabs
      files: '.*\.py'
    - id: remove-tabs
      files: '.*\.py'
      args: [ '--whitespaces-count', '4' ]
